# Generated by Django 5.1.6 on 2025-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.IntegerField(default=0),
        ),
    ]
